version: '3.5'
services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: readme-notify-fakesmtp
    hostname: fakesmtp
    ports:
      - "5025:5025"
      - "8083:5080"

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: readme-notify-rabbitmq
    ports:
      - '5672:5672'
      - '8084:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 12345
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo
    container_name: readme-notify-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: notify
    command: mongod --port 27019
    ports:
      - 27019:27019
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27019/notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: readme-notify-mongo-express
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongodb://admin:12345@mongodb:27019/
