# Создать публикацию
POST /blog/publications/ HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1NGRjNmM4MDQ1YjhlYWE2M2NhODYiLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peTQucnUiLCJmaXJzdE5hbWUiOiJGaWxpZG9yIiwibGFzdE5hbWUiOiJaZWxlbml5IiwiaWF0IjoxNjczOTc0MzQ5LCJleHAiOjE2NzM5NzUzNDl9.KlopwE0ZXed8xvODLmoyGkYSGJ5lYqe1QztRLlTCWnY
Content-Type: application/json

{
  "type": "Video",
  "tags": ["myvideo", "greatest", "myvideo"],
  "userId": "63bdbc988ae9bdcfce94e357",
  "content": {
    "title": "Приключения электроника",
    "videoLink": "www.youtube.com/electronic"
  }
}

# {
#   "type": "Photo",
#   "tags": ["myvideo", "greatest", "myvideo"],
#   "content": {
#     "photo": "default.jpg"
#   }
# }
###

# Редактировать публикацию
PATCH /blog/publications/10 HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhM0BydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiOWY3YjI3MGY0OTZjNjczODIyNzJjIiwibmFtZSI6IlZhbnlhIFJ1c3NpYW4iLCJhdmF0YXIiOiJSTjhkOTh1NVBDbU1CZGlTREdfcGIuanBlZyIsImlhdCI6MTY1NjgzNTYxMSwiZXhwIjoxNjU2ODc4ODExfQ.YHAwjl1xwaPXpAI2dTGAw2pX3sKnEUsWyVPdUlJsTAE
Content-Type: application/json

{
  "type": "Video",
  "tags": ["awesome", "прикалисы"],
  "isPublished": false,
  "content": {
    "title": "Гостья из будущего (Приключения Алисы)",
    "videoLink": "www.youtube.com/video"
  }
}
###

# Удалить публикацию
DELETE /blog/publications/19 HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhM0BydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiOWY3YjI3MGY0OTZjNjczODIyNzJjIiwibmFtZSI6IlZhbnlhIFJ1c3NpYW4iLCJhdmF0YXIiOiJSTjhkOTh1NVBDbU1CZGlTREdfcGIuanBlZyIsImlhdCI6MTY1NjgzNTYxMSwiZXhwIjoxNjU2ODc4ODExfQ.YHAwjl1xwaPXpAI2dTGAw2pX3sKnEUsWyVPdUlJsTAE
###

# Получить публикацию по ID
GET /blog/publications/4 HTTP/1.1
Host: localhost:3334
###

# Получить список публикаций (лимит, пагинация, сортировка, тэги, определенный пользователь)
# ?limit=50&page=0&sortType=date&sortDirection=desc&tags=sometag1,sometag2&user=63a9bb63c0068095cdd7706a&searchInTitle=""
GET /blog/publications?searchInTitle=При HTTP/1.1
Host: localhost:3334
###

# Получить список черновиков публикаций пользователя (лимит, пагинация, сортировка)
GET /blog/publications/users/drafts HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkYmM5ODhhZTliZGNmY2U5NGUzNTciLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peS5ydSIsImZpcnN0TmFtZSI6ItCk0LjQu9C40LTQvtGAIiwibGFzdE5hbWUiOiLQl9C10LvRkdC90YvQuSIsImlhdCI6MTY3Mzg2ODg4NywiZXhwIjoxNjczODY5MDY3fQ.WOp8P_Vq3hHZx46Od0Myp8Kfx3zjihy1Nu-kZdk0KVk
###

# Получить ленту публикаций (лимит, пагинация, сортировка)
GET /blog/publications/feed HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhM0BydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiOWY3YjI3MGY0OTZjNjczODIyNzJjIiwibmFtZSI6IlZhbnlhIFJ1c3NpYW4iLCJhdmF0YXIiOiJSTjhkOTh1NVBDbU1CZGlTREdfcGIuanBlZyIsImlhdCI6MTY1NjgzNTYxMSwiZXhwIjoxNjU2ODc4ODExfQ.YHAwjl1xwaPXpAI2dTGAw2pX3sKnEUsWyVPdUlJsTAE
###

# Поставить лайк публикации
POST /blog/publications/likes/2?isLike=true HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1NGRjNmM4MDQ1YjhlYWE2M2NhODYiLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peTQucnUiLCJmaXJzdE5hbWUiOiJGaWxpZG9yIiwibGFzdE5hbWUiOiJaZWxlbml5IiwiaWF0IjoxNjc0Mzg3MDU4LCJleHAiOjE2NzQzODgwNTh9.Ghq2A9M-VC4s0k7m4aM5MJiKbneVbNCZh7Ro2UP5kqY
###

# Удалить лайк публикации
POST /blog/publications/likes/2?isLike=false HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1NGRjNmM4MDQ1YjhlYWE2M2NhODYiLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peTQucnUiLCJmaXJzdE5hbWUiOiJGaWxpZG9yIiwibGFzdE5hbWUiOiJaZWxlbml5IiwiaWF0IjoxNjc0Mzg3MDU4LCJleHAiOjE2NzQzODgwNTh9.Ghq2A9M-VC4s0k7m4aM5MJiKbneVbNCZh7Ro2UP5kqY
###

# Сделать репост (копировать) публикации
POST /blog/publications/repost/1 HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1NGRjNmM4MDQ1YjhlYWE2M2NhODYiLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peTQucnUiLCJmaXJzdE5hbWUiOiJGaWxpZG9yIiwibGFzdE5hbWUiOiJaZWxlbml5IiwiaWF0IjoxNjc0Mzg0NjI2LCJleHAiOjE2NzQzODU2MjZ9.nYD1jxorvigJ6mL9Yne1VDZ36nkmcn3FVdeljXTS7AE
###

#  Загрузка фото для публикации
POST /blog/publications/43/photo/ HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1NGRjNmM4MDQ1YjhlYWE2M2NhODYiLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peTQucnUiLCJmaXJzdE5hbWUiOiJGaWxpZG9yIiwibGFzdE5hbWUiOiJaZWxlbml5IiwiaWF0IjoxNjczOTczODIyLCJleHAiOjE2NzM5NzQ4MjJ9.o329zIxRrDsq0oWzFks1pMDxPW0VkhudqLbKea-RQSg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="05.jpg"
Content-Type: image/jpeg

< D:/загрузки/05.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

#  Получить фото для публикации
GET /blog/publications/photo/056828.jpg HTTP/1.1
Host: localhost:3334
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1NGRjNmM4MDQ1YjhlYWE2M2NhODYiLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peTQucnUiLCJmaXJzdE5hbWUiOiJGaWxpZG9yIiwibGFzdE5hbWUiOiJaZWxlbml5IiwiaWF0IjoxNjczOTc0MDQ0LCJleHAiOjE2NzM5NzUwNDR9.-eEm3YzGdU3yL7YG-Wsdo8ZYpj0tW-TOeOsQnRu2UN4
###
